---
- name: cis
  hosts: windows
  tasks:
    - name: "1.1.2,CCE-37167-4 | Ensure 'Maximum password age' is set to '60 or fewer days, but not 0' [GSA-90]"
      win_security_policy:
        section: System Access
        key: MaximumPasswordAge
        value: 90
