---
- name: cis
  hosts: windows
  tasks:
    - name: "1.1.2,CCE-37167-4 | Ensure 'Maximum password age' is set to '60 or fewer days, but not 0' [GSA-90]"
      win_security_policy:
        section: System Access
        key: MaximumPasswordAge
        value: 90
 
    - name: "9.1.3,CCE-36146-9 | Ensure 'Windows Firewall - Domain - Outbound connections' is set to 'Allow (default)'"
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
        name: "DefaultOutboundAction"
        data: "0"
        type: dword
 
    - name: "2.2.10,CCE-35912-5 | Ensure 'Back up files and directories' is set to 'Administrators'"
      win_user_right:
        name: SeBackupPrivilege
        users:
        - Administrators
        action: set
    

