---
- name: cli command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: run command expecting user confirmation
      ansible.netcommon.cli_command:
        command: show interface summary
        prompt: Press any key to continue
        answer: y
        newline: false
